
packages:
- java
- nc

write_files:

- path: /run/ssm.sh
  permissions: 0700
  content: |
    #!/bin/bash
    echo Installing SSM Agent
    #!/bin/bash
    sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    sudo systemctl enable amazon-ssm-agent
    sudo systemctl start amazon-ssm-agent

runcmd:
- /run/ssm.sh

